blueprint:
  custom_cards:
  - mushroom-title-card
  - mushroom-template-card
  - mushroom-entity-card
  - mini-graph-card
  - bar-card
  - stack-in-card
  - fold-entity-row
  - restriction-card
  description: Systemmonitor page by Bourner
  name: Systemmonitor Page Blueprint
  type: page
  version: '2.0'
card:
  cards:
    - cards:
        - subtitle: Shortcuts
          type: custom:mushroom-title-card
        - primary: Reload Dwains Dashboard
          type: custom:mushroom-template-card
          icon: mdi:alpha-d-box
          icon_color: blue
          entity: ''
          tap_action:
            action: call-service
            service: dwains_dashboard.reload
            service_data: {}
            target: {}
        - type: custom:restriction-card
          locked_icon: mdi:lock-outline
          unlocked_icon: mdi:lock-open-variant-outline
          action: hold
          card:
            primary: Restart Home Assistant
            type: custom:mushroom-template-card
            icon: mdi:home-assistant
            icon_color: blue
            entity: ''
            tap_action:
              action: call-service
              service: homeassistant.restart
              service_data: {}
              target: {}
        - primary: Logs
          type: custom:mushroom-template-card
          icon: mdi:math-log
          icon_color: white
          entity: ''
          tap_action:
            action: navigate
            navigation_path: /config/logs
        - primary: HACS
          type: custom:mushroom-template-card
          icon: hacs:hacs
          icon_color: white
          entity: ''
          tap_action:
            action: navigate
            navigation_path: /hacs/entry
        - primary: File Editor
          type: custom:mushroom-template-card
          icon: mdi:wrench
          icon_color: white
          entity: ''
          tap_action:
            action: navigate
            navigation_path: /core_configurator/dashboard
        - primary: Terminal
          type: custom:mushroom-template-card
          icon: mdi:console
          icon_color: white
          entity: ''
          tap_action:
            action: navigate
            navigation_path: /core_ssh/dashboard
        - primary: Developer Tools
          type: custom:mushroom-template-card
          icon: mdi:hammer
          icon_color: white
          entity: ''
          tap_action:
            action: navigate
            navigation_path: /developer-tools/state
        - type: conditional
          conditions:
            - entity: update.home_assistant_core_update
              state: 'on'
          card:
            type: custom:mushroom-update-card
            entity: update.home_assistant_core_update
            use_entity_picture: true
            fill_container: false
            collapsible_controls: true
            show_buttons_control: true
      item_classes: col-lg-3 col-xs-12
      type: vertical-stack
    - cards:
        - subtitle: Speedtest
          type: custom:mushroom-title-card
        - entities:
            - sensor.speedtest_ping
          font_size: 70
          height: 30
          hours_to_show: 168
          icon: mdi:pulse
          line_color: var(--primary-color)
          line_width: 2
          name: Ping
          points_per_hour: 1
          show:
            fill: true
            graph: bar
          type: custom:mini-graph-card
        - cards:
            - entities:
                - entity: sensor.speedtest_download
                  show_points: false
              font_size: 70
              hours_to_show: 168
              icon: mdi:arrow-down-bold
              line_color: var(--primary-color)
              line_width: 2
              name: Download
              show:
                extrema: true
                labels: false
              type: custom:mini-graph-card
            - entities:
                - entity: sensor.speedtest_upload
                  show_points: false
              font_size: 70
              hours_to_show: 168
              icon: mdi:arrow-up-bold
              line_color: var(--primary-color)
              line_width: 2
              name: Upload
              show:
                extrema: true
                labels: false
              type: custom:mini-graph-card
          type: horizontal-stack
        - subtitle: System
          type: custom:mushroom-title-card
        - cards:
            - entity: sensor.ipv4_address_eth0
              name: IP Adress
              type: custom:mushroom-entity-card
            - entity: sensor.last_boot
              type: custom:mushroom-entity-card
          type: horizontal-stack
        - cards:
            - bar_style:
                border-radius: 5px
                padding-left: 4px
                text-align: left
              columns: 2
              entities:
                - entity: sensor.processor_use
                - entity: sensor.memory_use_percent
                - entity: sensor.processor_temperature
                  icon: mdi:thermometer
                - entity: sensor.disk_use_percent
              positions:
                indicator: inside
                name: 'off'
              severity:
                - color: Green
                  from: 0
                  to: 60
                - color: Orange
                  from: 61
                  to: 80
                - color: Red
                  from: 81
                  to: 100
              style: |
                ha-card {
                  border-radius: 5px;
                }
                bar-card-backgroundbar, bar-card-currentbar {
                  border-radius: 5px;
                }
                bar-card-value {
                  font-weight: bold;
                }
                bar-card-iconbar {
                  height: 20px;
                }      
              type: custom:bar-card
          type: horizontal-stack
        - cards:
            - entities:
                - sensor.network_throughput_in_eth0
              font_size: 70
              hours_to_show: 24
              points_per_hour: 5
              icon: mdi:arrow-down-bold
              line_color: var(--primary-color)
              line_width: 2
              icon_adaptive_color: true
              name: Throughput In
              show:
                labels: false
              type: custom:mini-graph-card
            - entities:
                - sensor.network_throughput_out_eth0
              font_size: 70
              hours_to_show: 24
              points_per_hour: 5
              icon: mdi:arrow-up-bold
              line_color: var(--primary-color)
              line_width: 2
              name: Throughput Out
              show:
                labels: false
              type: custom:mini-graph-card
          type: horizontal-stack
      item_classes: col-lg-6 col-xs-12
      type: vertical-stack
    - cards:
        - subtitle: Server Controls
          type: custom:mushroom-title-card
        - cards:
            - primary: Home Assistant Cloud
              type: custom:mushroom-template-card
              icon: mdi:cloud-lock
              icon_color: teal
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/cloud/login
            - primary: Devices & Services
              type: custom:mushroom-template-card
              icon: mdi:devices
              icon_color: '#00008b'
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/integrations
            - primary: Automations & Scenes
              type: custom:mushroom-template-card
              icon: mdi:robot
              icon_color: green
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/automation/dashboard
            - primary: Areas & Zones
              type: custom:mushroom-template-card
              icon: mdi:sofa
              icon_color: orange
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/areas/dashboard
            - primary: Add-ons
              type: custom:mushroom-template-card
              icon: mdi:puzzle
              icon_color: yellow
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /hassio/dashboard
            - primary: Dashboards
              type: custom:mushroom-template-card
              icon: mdi:view-dashboard
              icon_color: pink
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/lovelace/dashboards
            - primary: NFC Tags
              type: custom:mushroom-template-card
              icon: mdi:nfc-variant
              icon_color: grey
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/tags
            - primary: Persons
              type: custom:mushroom-template-card
              icon: mdi:account
              icon_color: blue
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/person
            - primary: System
              type: custom:mushroom-template-card
              icon: mdi:cog
              icon_color: purple
              entity: ''
              tap_action:
                action: navigate
                navigation_path: /config/system
          type: custom:stack-in-card
        - entities:
            - head:
                type: section
                label: Reload Scripts
              type: custom:fold-entity-row
              padding: 0
              entities:
                - cards:
                    - primary: Reload Automations
                      type: custom:mushroom-template-card
                      icon: mdi:robot
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: automation.reload
                        service_data: {}
                        target: {}
                    - primary: Reload Scripts
                      type: custom:mushroom-template-card
                      icon: mdi:script-text
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: script.reload
                        service_data: {}
                        target: {}
                    - primary: Reload Groups
                      type: custom:mushroom-template-card
                      icon: mdi:google-circles-communities
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: group.reload
                        service_data: {}
                        target: {}
                    - primary: Reload Persons
                      type: custom:mushroom-template-card
                      icon: mdi:account
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: person.reload
                        service_data: {}
                        target: {}
                    - primary: Reload Scenes
                      type: custom:mushroom-template-card
                      icon: mdi:palette
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: scene.reload
                        service_data: {}
                        target: {}
                    - primary: Reload Zones
                      type: custom:mushroom-template-card
                      icon: mdi:map-marker
                      icon_color: blue
                      entity: ''
                      tap_action:
                        action: call-service
                        service: zone.reload
                        service_data: {}
                        target: {}
                  type: custom:stack-in-card
          style:
            '#states':
              $: null
              fold-entity-row:
                $:
                  '#head':
                    hui-section-row:
                      $: |
                        .divider {
                          opacity: 0 !important;
                        }
          type: entities
      item_classes: col-lg-3 col-xs-12
      type: vertical-stack
  items_classes: col-xs-12
  type: custom:dwains-flexbox-card
  
