blueprint:
  custom_cards:
  - button-card
  description: adds homekit style conditional media monitors card by Bourner
  name: Homekit Conditional Media Monitors Card
  type: replace-card
  version: '1.0'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  type: custom:button-card
  template:
    - conditional_media
    - icon_monitors
