blueprint:
  custom_cards:
  - button-card
  description: adds homekit style person card by Bourner
  name: Homekit Person Card
  type: replace-card
  version: '1.0'
card:
  entity: $replace_with_input_entity$
  name: $replace_with_input_name$
  type: custom:button-card
  template:
    - person
